apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-10-01T16:13:55Z'
  generation: 9
  labels:
    app: tyk-pump
  name: tyk-pump
  namespace: tyk-pro-demo
  resourceVersion: '39812200'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/tyk-pro-demo/deploymentconfigs/tyk-pump
  uid: 77b0fed3-e466-11e9-9912-005056941cd3
spec:
  replicas: 1
  selector:
    app: tyk-pump
    deploymentconfig: tyk-pump
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: tyk-pump
        deploymentconfig: tyk-pump
    spec:
      containers:
        - image: >-
            tykio/tyk-pump-docker-pub@sha256:cbbcc53214b8a4780b731fbe92a9e6e9ca2527226ef22c3b619e1755bc00e39e
          imagePullPolicy: Always
          name: tyk-pump
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/tyk-pump/pump.conf
              name: volume-debtw
              subPath: pump.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: pump-conf
          name: volume-debtw
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - tyk-pump
        from:
          kind: ImageStreamTag
          name: 'tyk-pump:latest'
          namespace: tyk-pro-demo
        lastTriggeredImage: >-
          tykio/tyk-pump-docker-pub@sha256:cbbcc53214b8a4780b731fbe92a9e6e9ca2527226ef22c3b619e1755bc00e39e
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-10-02T15:05:27Z'
      lastUpdateTime: '2019-10-02T15:05:27Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-10-02T15:05:28Z'
      lastUpdateTime: '2019-10-02T15:05:28Z'
      message: replication controller "tyk-pump-8" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: Manual
    message: manual change
  latestVersion: 8
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
