apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-10-01T15:55:09Z'
  generation: 2
  labels:
    app: tyk-redis
  name: tyk-redis
  namespace: tyk-pro-demo
  resourceVersion: '39444014'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/tyk-pro-demo/deploymentconfigs/tyk-redis
  uid: d8ab2164-e463-11e9-9912-005056941cd3
spec:
  replicas: 1
  selector:
    app: tyk-redis
    deploymentconfig: tyk-redis
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: tyk-redis
        deploymentconfig: tyk-redis
    spec:
      containers:
        - image: >-
            redis@sha256:4332745b2116859f4b77ff9dbc57ad9f5327dfe5e65807e064bdd2fe7c3cbfef
          imagePullPolicy: Always
          name: tyk-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: tyk-redis-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tyk-redis-1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - tyk-redis
        from:
          kind: ImageStreamTag
          name: 'tyk-redis:latest'
          namespace: tyk-pro-demo
        lastTriggeredImage: >-
          redis@sha256:4332745b2116859f4b77ff9dbc57ad9f5327dfe5e65807e064bdd2fe7c3cbfef
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-10-01T15:55:22Z'
      lastUpdateTime: '2019-10-01T15:55:22Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-10-01T15:55:23Z'
      lastUpdateTime: '2019-10-01T15:55:23Z'
      message: replication controller "tyk-redis-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
