apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-10-01T16:13:26Z'
  labels:
    app: tyk-gateway
  name: tyk-gateway
  namespace: tyk-pro-demo
  resourceVersion: '39448898'
  selfLink: /api/v1/namespaces/tyk-pro-demo/services/tyk-gateway
  uid: 66022996-e466-11e9-9912-005056941cd3
spec:
  clusterIP: 172.30.186.98
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: tyk-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
