apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-10-01T16:14:26Z'
  labels:
    app: mongo
  name: mongo
  namespace: tyk-pro-demo
  resourceVersion: '39449267'
  selfLink: /api/v1/namespaces/tyk-pro-demo/services/mongo
  uid: 8a1c59a5-e466-11e9-9912-005056941cd3
spec:
  clusterIP: 172.30.151.10
  ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    deploymentconfig: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
