apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-10-01T15:55:09Z'
  labels:
    app: tyk-redis
  name: tyk-redis
  namespace: tyk-pro-demo
  resourceVersion: '39443928'
  selfLink: /api/v1/namespaces/tyk-pro-demo/services/tyk-redis
  uid: d8ad43fc-e463-11e9-9912-005056941cd3
spec:
  clusterIP: 172.30.121.70
  ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    deploymentconfig: tyk-redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
