apiVersion: v1
data:
  pump.conf: |-
    {
      "analytics_storage_type": "redis",
      "analytics_storage_config": {
        "type": "redis",
        "host": "tyk-redis.tyk-pro-demo.svc",
        "port": 6379,
        "hosts": null,
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100,
        "optimisation_max_active": 100,
        "enable_cluster": false
      },
      "purge_delay": 2,
      "pumps": {
        "mongo": {
          "name": "mongo",
          "meta": {
            "collection_name": "tyk_analytics",
            "mongo_url": "mongodb://mongo.tyk-pro-demo.svc :27017/tyk_analytics",
            "max_insert_batch_size_bytes": 80000,
            "max_document_size_bytes": 20112
          }
        },
        "mongo-pump-aggregate": {
          "name": "mongo-pump-aggregate",
          "meta": {
            "mongo_url": "mongodb://mongo.tyk-pro-demo.svc :27017/tyk_analytics"
          },
          "use_mixed_collection": true
        },
        "mongo-pump-selective": {
          "name": "mongo-pump-selective",
          "meta": {
            "mongo_url": "mongodb://mongo.tyk-pro-demo.svc :27017/tyk_analytics"
          },
          "use_mixed_collection": true
        }
      },
      "uptime_pump_config": {
        "collection_name": "tyk_uptime_analytics",
        "mongo_url": "mongodb://mongo.tyk-pro-demo.svc :27017/tyk_analytics",
        "max_insert_batch_size_bytes": 500000,
        "max_document_size_bytes": 200000
      },
      "dont_purge_uptime_data": false
    }
kind: ConfigMap
metadata:
  creationTimestamp: '2019-10-01T16:49:09Z'
  name: pump-conf
  namespace: tyk-pro-demo
  resourceVersion: '39812025'
  selfLink: /api/v1/namespaces/tyk-pro-demo/configmaps/pump-conf
  uid: 635c6422-e46b-11e9-9912-005056941cd3
