apiVersion: v1
data:
  tyk_analytics.conf: |-
    {
      "listen_port": 3000,
      "tyk_api_config": {
        "Host": "http://tyk-gateway.tyk-pro-demo.svc",
        "Port": "8080",
        "Secret": "352d20ee67be67f6340b4c0605b044b7"
      },
      "mongo_url": "mongodb://mongo.tyk-pro-demo.svc:27017/tyk_analytics",
      "page_size": 10,
      "admin_secret": "12345",
      "shared_node_secret": "352d20ee67be67f6340b4c0605b044b7",
      "redis_port": 6379,
      "redis_host": "tyk-redis.tyk-pro-demo.svc",
      "redis_password": "",
      "enable_cluster": false,
      "force_api_defaults": false,
      "notify_on_change": true,
      "license_key": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX25vZGVzIjoiNmE5OTY5YWEtNjdkYi00NDJkLTRjOTktNmZhN2EwZjdhYWM5IiwiZXhwIjoxNTc3MTMwMjQyLCJpYXQiOjE1NjkzNTQyNDIsIm93bmVyIjoiNWQ4YTcyMDE0NWY5MmU0ZjVjNzRlNTM1Iiwic2NvcGUiOiJ0cmFjayIsInYiOiIyIn0.HWYqWYHZsTZUKQAEN3qM6LA_rVRsDCj6HX-wVlN_ndmGhwZkY8Rj9ONJ92BsNN5HrBdXh38anEzGl39d9dYAonzUftMpEsYpm9SAG7U5qtlz8w-Qp3_ifV5CayWqqldF1l4o_7PpynjbI-i8YsB3jNZP4YUIz08FUFRQAIFk8uG4cBsZ11hUpIMgjSmHL2Epuf6ait8EIVYiPeLuqfkccK2-urbUTSz1wsi8Bx-4wjBn4VTKSnowe3nt7mHjFBtQOlHjU1MFb69Gq4G7_vY5TKsvaPOoeixmpXEZbvrXqkRd10fqzNkkoB3YpP0KtlrXMN34-pM6hkqYooTJohK6EA",
      "redis_database": 0,
      "redis_hosts": null,
      "hash_keys": true,
      "email_backend": {
        "enable_email_notifications": false,
        "code": "sendgrid",
        "settings": {
          "ClientKey": ""
        },
        "default_from_email": "you@somewhere.com",
        "default_from_name": "Some Person"
      },
      "hide_listen_path": false,
      "sentry_code": "",
      "sentry_js_code": "",
      "use_sentry": false,
      "enable_master_keys": false,
      "enable_duplicate_slugs": true,
      "show_org_id": true,
      "host_config": {
        "enable_host_names": true,
        "disable_org_slug_prefix": true,
        "hostname": "www.tyk-test.com",
        "override_hostname": "www.tyk-test.com:8080",
        "portal_domains": {},
        "portal_root_path": "/portal",
        "generate_secure_paths": false,
        "use_strict_hostmatch": false
      },
      "http_server_options": {
        "use_ssl": false,
        "certificates": [],
        "min_version": 0
      },
      "ui": {
        "languages": {
          "Chinese": "cn",
          "English": "en",
          "Korean": "ko"
        },
        "hide_help": true,
        "default_lang": "en",
        "login_page": {},
        "nav": {
          "dont_show_admin_sockets": false,
          "hide_activity_by_api_section": false,
          "hide_geo": false,
          "hide_licenses_section": false,
          "hide_logs": false,
          "hide_tib_section": false
        },
        "uptime": {},
        "portal_section": null,
        "designer": {},
        "dont_show_admin_sockets": false,
        "dont_allow_license_management": false,
        "dont_allow_license_management_view": false
      },
      "home_dir": "/opt/tyk-dashboard",
      "tagging_options": {
        "tag_all_apis_by_org": false
      },
      "use_sharded_analytics": true,
      "enable_aggregate_lookups": true,
      "enable_analytics_cache": false,
      "aggregate_lookup_cutoff": "26/05/2016",
      "maintenance_mode": false,
      "allow_explicit_policy_id": true,
      "private_key_path": "",
      "node_schema_path": "",
      "oauth_redirect_uri_separator": ";",
      "statsd_connection_string": "",
      "statsd_prefix": ""
    }
kind: ConfigMap
metadata:
  creationTimestamp: '2019-10-01T16:45:02Z'
  name: tyk-analytics-conf
  namespace: tyk-pro-demo
  resourceVersion: '39819680'
  selfLink: /api/v1/namespaces/tyk-pro-demo/configmaps/tyk-analytics-conf
  uid: d09e5090-e46a-11e9-9912-005056941cd3
